[package]
name = "day_07"
version = "0.1.0"
authors = ["Adam Lesperance <lespea@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bus = "2"
crossbeam = "0"
intcode = {version = "0", path="../intcode"}
